categories = [
    "Alimentos y Bebidas",
    "Asesoría y Consultoría",
    "Automotriz",
    "Belleza y Cuidado Personal",
    "Construcción y Remodelación",
    "Contabilidad y Finanzas",
    "Diseño y Creatividad",
    "Educación y Capacitación",
    "Entretenimiento y Eventos",
    "Hogar y Jardinería",
    "Imprenta y Publicidad",
    "Inmobiliarias",
    "Informática y Tecnología",
    "Legal y Jurídico",
    "Limpieza y Mantenimiento",
    "Logística y Transporte",
    "Mascotas",
    "Mobiliario y Oficina",
    "Recursos Humanos",
    "Reparaciones y Servicios Técnicos",
    "Restaurantes y Cafeterías",
    "Ropa y Accesorios",
    "Salud y Bienestar",
    "Seguridad",
    "Telecomunicaciones",
    "Viajes y Turismo"
]